2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-23 19:28:20 - ERROR - 17504 - [wt_gateway_service.py] - wt_gateway_service - 295 - Connectors - not found! Check your configuration!
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 297 - Remote configuration is enabled forcibly!
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device VZ116_M11 - connector Emerson-Modbus113-TCP from persistent device storage - not found.
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device VZ116_M21 - connector Emerson-Modbus113-TCP from persistent device storage - not found.
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 升降机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 循环风机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 输送机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:28:20 - INFO - 17504 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-23 19:28:20 - ERROR - 31828 - [wt_gateway_remote_configurator.py] - wt_gateway_remote_configurator - 112 - 'separator'
Traceback (most recent call last):
  File "D:\Project\wthings\wthings-gateway\wthings_gateway\gateway\wt_gateway_remote_configurator.py", line 88, in wt_process_configuration
    conf = process_extend(configuration, self.__old_general_configuration_file, self.__old_logs_configuration)
  File "D:\Project\wthings\wthings-gateway\wthings_gateway\wt_utility\wt_expand_parse.py", line 399, in process_extend
    opcda_expand = OpcDAExpand(v["configuration"]["servers"], v["id"])
  File "D:\Project\wthings\wthings-gateway\wthings_gateway\wt_utility\wt_expand_parse.py", line 94, in __init__
    "separator": m["separator"],
KeyError: 'separator'
2020-09-23 19:28:20 - INFO - 31828 - [wt_gateway_service.py] - wt_gateway_service - 207 - on_applied_configuration
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-23 19:32:02 - ERROR - 13012 - [wt_gateway_service.py] - wt_gateway_service - 295 - Connectors - not found! Check your configuration!
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 297 - Remote configuration is enabled forcibly!
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device VZ116_M11 - connector Emerson-Modbus113-TCP from persistent device storage - not found.
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device VZ116_M21 - connector Emerson-Modbus113-TCP from persistent device storage - not found.
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 升降机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 循环风机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 654 - Pair device 输送机 - connector Emerson-Modbus-TCP from persistent device storage - not found.
2020-09-23 19:32:02 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-23 19:32:50 - INFO - 12508 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-23 19:32:50 - INFO - 12508 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-23 19:32:50 - ERROR - 12508 - [wt_gateway_service.py] - wt_gateway_service - 295 - Connectors - not found! Check your configuration!
2020-09-23 19:32:50 - INFO - 12508 - [wt_gateway_service.py] - wt_gateway_service - 297 - Remote configuration is enabled forcibly!
2020-09-23 19:32:50 - INFO - 12508 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 09:56:42 - INFO - 35828 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 09:56:42 - INFO - 35828 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 09:56:43 - ERROR - 35828 - [wt_gateway_service.py] - wt_gateway_service - 314 - 'modbus'
Traceback (most recent call last):
  File "D:\Project\wthings\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 306, in _connect_with_connectors
    connector = self._implemented_connectors[connector_type](self, connector_config["config"][config],
KeyError: 'modbus'
2020-09-24 09:56:43 - INFO - 35828 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 09:58:39 - INFO - 6992 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 09:58:39 - INFO - 6992 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 09:58:40 - ERROR - 6992 - [wt_gateway_service.py] - wt_gateway_service - 309 - 'modbus'
Traceback (most recent call last):
  File "D:\Project\wthings\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 301, in _connect_with_connectors
    connector = self._implemented_connectors[connector_type](self, connector_config["config"][config],
KeyError: 'modbus'
2020-09-24 09:58:40 - INFO - 6992 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 10:48:35 - INFO - 22740 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 10:48:35 - INFO - 22740 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 10:48:35 - INFO - 22740 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 10:48:35 - INFO - 22740 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 11:15:49 - INFO - 27764 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 11:15:49 - INFO - 27764 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 11:15:49 - INFO - 27764 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 11:15:49 - INFO - 27764 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 11:16:49 - INFO - 16444 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 11:16:49 - INFO - 16444 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 11:16:49 - INFO - 16444 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 11:16:49 - INFO - 16444 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 11:18:29 - INFO - 27356 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 11:18:29 - INFO - 27356 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 11:18:29 - INFO - 27356 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 11:18:29 - INFO - 27356 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 13:28:30 - INFO - 24836 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:28:30 - INFO - 24836 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:28:31 - INFO - 24836 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:28:31 - INFO - 24836 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 13:29:29 - INFO - 16212 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:29:29 - INFO - 16212 - [wt_gateway_service.py] - wt_gateway_service - 79 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:29:29 - INFO - 16212 - [wt_gateway_service.py] - wt_gateway_service - 650 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:29:29 - INFO - 16212 - [wt_gateway_service.py] - wt_gateway_service - 138 - Gateway started.
2020-09-24 13:38:49 - INFO - 22536 - [wt_gateway_service.py] - wt_gateway_service - 73 - Gateway starting...
2020-09-24 13:39:27 - INFO - 25268 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:39:42 - INFO - 26180 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:39:59 - INFO - 25912 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:39:59 - INFO - 25912 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:40:12 - INFO - 30180 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:40:12 - INFO - 30180 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:40:13 - INFO - 30180 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:40:13 - INFO - 30180 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:42:11 - INFO - 27804 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:42:11 - INFO - 27804 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:42:11 - INFO - 27804 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:42:11 - INFO - 27804 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:43:20 - INFO - 24692 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:43:20 - INFO - 24692 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:43:20 - INFO - 24692 - [wt_gateway_service.py] - wt_gateway_service - 642 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:43:20 - INFO - 24692 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:44:39 - INFO - 25128 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:44:39 - INFO - 25128 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:44:39 - INFO - 25128 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:44:39 - INFO - 25128 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:45:25 - INFO - 19204 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:45:25 - INFO - 19204 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:45:25 - INFO - 19204 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:45:25 - INFO - 19204 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:48:04 - INFO - 13580 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:48:04 - INFO - 13580 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:48:04 - INFO - 13580 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:48:04 - INFO - 13580 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:51:15 - INFO - 31400 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:51:15 - INFO - 31400 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:51:15 - INFO - 31400 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:51:15 - INFO - 31400 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:56:14 - INFO - 21344 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:56:14 - INFO - 21344 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:56:14 - INFO - 21344 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:56:14 - INFO - 21344 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:57:25 - INFO - 25148 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:57:25 - INFO - 25148 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:57:25 - INFO - 25148 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:57:25 - INFO - 25148 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 13:58:18 - INFO - 32980 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 13:58:18 - INFO - 32980 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 13:58:18 - INFO - 32980 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 13:58:18 - INFO - 32980 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:00:23 - INFO - 32 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:00:23 - INFO - 32 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:00:23 - INFO - 32 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:00:23 - INFO - 32 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:03:17 - INFO - 21680 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:03:17 - INFO - 21680 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:03:18 - INFO - 21680 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:03:18 - INFO - 21680 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:06:21 - INFO - 28724 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:06:21 - INFO - 28724 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:06:21 - INFO - 28724 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:06:21 - INFO - 28724 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:45:12 - INFO - 6056 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:45:12 - INFO - 6056 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:45:12 - INFO - 6056 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:45:12 - INFO - 6056 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:45:48 - INFO - 27704 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:45:48 - INFO - 27704 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:45:48 - INFO - 27704 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:45:48 - INFO - 27704 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:47:27 - INFO - 21028 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:47:27 - INFO - 21028 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:47:27 - INFO - 21028 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:47:27 - INFO - 21028 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:49:20 - INFO - 32764 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:49:20 - INFO - 32764 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:49:21 - INFO - 32764 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:49:21 - INFO - 32764 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:50:09 - INFO - 1200 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:50:09 - INFO - 1200 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:50:09 - INFO - 1200 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:50:09 - INFO - 1200 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:53:13 - INFO - 25732 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:53:13 - INFO - 25732 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:53:13 - INFO - 25732 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:53:13 - INFO - 25732 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 14:54:39 - INFO - 6564 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 14:54:39 - INFO - 6564 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 14:54:39 - INFO - 6564 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 14:54:39 - INFO - 6564 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 16:31:54 - INFO - 3872 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 16:31:54 - INFO - 3872 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 16:31:54 - INFO - 3872 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 16:31:54 - INFO - 3872 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-24 17:09:00 - INFO - 30328 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-24 17:09:00 - INFO - 30328 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-24 17:09:00 - INFO - 30328 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-24 17:09:00 - INFO - 30328 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 09:26:50 - INFO - 5816 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 09:26:50 - INFO - 5816 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 09:26:51 - INFO - 5816 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 09:26:51 - INFO - 5816 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 09:27:25 - INFO - 14048 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 09:27:25 - INFO - 14048 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 09:27:25 - INFO - 14048 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 09:27:25 - INFO - 14048 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 09:34:50 - INFO - 14196 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 09:34:50 - INFO - 14196 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 09:34:51 - INFO - 14196 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 09:34:51 - INFO - 14196 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 09:35:55 - INFO - 4644 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 09:35:55 - INFO - 4644 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 09:35:55 - INFO - 4644 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 09:35:55 - INFO - 4644 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 10:57:15 - INFO - 2432 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 10:57:15 - INFO - 2432 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 10:57:16 - INFO - 2432 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 10:57:16 - INFO - 2432 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 10:57:48 - INFO - 14044 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 10:57:48 - INFO - 14044 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 10:57:48 - INFO - 14044 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 10:57:48 - INFO - 14044 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:02:51 - INFO - 3492 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:02:51 - INFO - 3492 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:02:52 - INFO - 3492 - [wt_gateway_service.py] - wt_gateway_service - 642 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 11:02:52 - INFO - 3492 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:03:09 - INFO - 14232 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:03:09 - INFO - 14232 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:03:10 - INFO - 14232 - [wt_gateway_service.py] - wt_gateway_service - 642 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 11:03:10 - INFO - 14232 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:05:19 - INFO - 15096 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:05:19 - INFO - 15096 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:05:19 - INFO - 15096 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:11:16 - INFO - 14392 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:11:16 - INFO - 14392 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:11:16 - INFO - 14392 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 11:11:16 - INFO - 14392 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:13:24 - INFO - 12316 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:13:24 - INFO - 12316 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:13:24 - INFO - 12316 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector modbus-rtu from persistent device storage - not found.
2020-09-25 11:13:24 - INFO - 12316 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:24:33 - INFO - 14268 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:24:33 - INFO - 14268 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:24:34 - INFO - 14268 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:27:36 - INFO - 14584 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:27:36 - INFO - 14584 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:27:36 - INFO - 14584 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:28:01 - INFO - 11336 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:28:01 - INFO - 11336 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:28:01 - INFO - 11336 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:28:23 - INFO - 10256 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:28:23 - INFO - 10256 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:28:23 - INFO - 10256 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:29:49 - INFO - 10276 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:29:49 - INFO - 10276 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:29:49 - INFO - 10276 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:32:57 - INFO - 14564 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:32:57 - INFO - 14564 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:32:58 - INFO - 14564 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:36:23 - INFO - 6044 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:36:23 - INFO - 6044 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:36:24 - INFO - 6044 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:36:40 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:41 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:42 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:43 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:44 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:45 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:46 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:47 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:48 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:49 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:50 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:51 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:52 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:53 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:54 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:55 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:56 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:57 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:58 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:36:59 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:00 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:01 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:02 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:03 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:04 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:05 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:06 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:07 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:08 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:09 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:10 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:11 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:12 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:13 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:14 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:15 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:16 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:17 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:18 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:19 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:20 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:37:21 - ERROR - 3632 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 11:38:22 - INFO - 16264 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:38:22 - INFO - 16264 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:38:22 - INFO - 16264 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:41:45 - INFO - 15716 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:41:45 - INFO - 15716 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:41:45 - INFO - 15716 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:42:07 - INFO - 16344 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:42:07 - INFO - 16344 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:42:07 - INFO - 16344 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:48:08 - INFO - 15396 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:48:08 - INFO - 15396 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:48:09 - INFO - 15396 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:50:41 - INFO - 15676 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:50:41 - INFO - 15676 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:50:42 - INFO - 15676 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:55:49 - INFO - 15204 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:55:49 - INFO - 15204 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:55:50 - INFO - 15204 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 11:56:26 - INFO - 16284 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 11:56:26 - INFO - 16284 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 11:56:26 - INFO - 16284 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:09:04 - INFO - 5024 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:09:04 - INFO - 5024 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:09:04 - INFO - 5024 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:19:39 - INFO - 3552 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:19:39 - INFO - 3552 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:22:34 - INFO - 9092 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:22:34 - INFO - 9092 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:22:34 - INFO - 9092 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:33:38 - INFO - 14204 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:33:38 - INFO - 14204 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:33:38 - INFO - 14204 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:33:50 - INFO - 9928 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:33:50 - INFO - 9928 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:33:51 - INFO - 9928 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:42:53 - INFO - 1916 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:42:53 - INFO - 1916 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:42:53 - INFO - 1916 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:44:59 - INFO - 15116 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:44:59 - INFO - 15116 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:44:59 - INFO - 15116 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:46:46 - INFO - 9812 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:46:46 - INFO - 9812 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:46:46 - INFO - 9812 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:53:56 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:53:56 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:53:56 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 13:55:11 - INFO - 15500 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 13:55:11 - INFO - 15500 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 13:55:11 - INFO - 15500 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:06:07 - INFO - 13436 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:06:07 - INFO - 13436 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:06:07 - ERROR - 16176 - [wt_gateway_service.py] - wt_gateway_service - 423 - 'NoneType' object has no attribute 'in_process'
Traceback (most recent call last):
  File "D:\Project\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 353, in __read_data_from_storage
    print("", self.__remote_configurator, self.__remote_configurator.in_process)
AttributeError: 'NoneType' object has no attribute 'in_process'
2020-09-25 14:06:07 - INFO - 13436 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:06:08 - ERROR - 16176 - [wt_gateway_service.py] - wt_gateway_service - 423 - 'NoneType' object has no attribute 'in_process'
Traceback (most recent call last):
  File "D:\Project\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 353, in __read_data_from_storage
    print("", self.__remote_configurator, self.__remote_configurator.in_process)
AttributeError: 'NoneType' object has no attribute 'in_process'
2020-09-25 14:06:09 - ERROR - 16176 - [wt_gateway_service.py] - wt_gateway_service - 423 - 'NoneType' object has no attribute 'in_process'
Traceback (most recent call last):
  File "D:\Project\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 353, in __read_data_from_storage
    print("", self.__remote_configurator, self.__remote_configurator.in_process)
AttributeError: 'NoneType' object has no attribute 'in_process'
2020-09-25 14:06:10 - ERROR - 16176 - [wt_gateway_service.py] - wt_gateway_service - 423 - 'NoneType' object has no attribute 'in_process'
Traceback (most recent call last):
  File "D:\Project\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 353, in __read_data_from_storage
    print("", self.__remote_configurator, self.__remote_configurator.in_process)
AttributeError: 'NoneType' object has no attribute 'in_process'
2020-09-25 14:06:11 - ERROR - 16176 - [wt_gateway_service.py] - wt_gateway_service - 423 - 'NoneType' object has no attribute 'in_process'
Traceback (most recent call last):
  File "D:\Project\wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 353, in __read_data_from_storage
    print("", self.__remote_configurator, self.__remote_configurator.in_process)
AttributeError: 'NoneType' object has no attribute 'in_process'
2020-09-25 14:06:53 - INFO - 17220 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:06:53 - INFO - 17220 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:06:53 - INFO - 17220 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:18:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:15 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:16 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:17 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:18 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:19 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:20 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:21 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:22 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:23 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:24 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:25 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:26 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:27 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:28 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:29 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:30 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:31 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:32 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:33 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:34 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:35 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:36 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:37 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:38 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:39 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:40 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:41 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:42 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:44 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:45 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:46 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:47 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:48 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:49 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:50 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:51 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:52 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:53 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:54 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:55 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:56 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:57 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:58 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:18:59 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:00 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:01 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:02 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:03 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:04 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:05 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:06 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:07 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:08 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:09 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:10 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:15 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:16 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:17 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:18 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:19 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:20 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:21 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:22 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:23 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:24 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:25 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:26 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:27 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:28 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:29 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:30 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:31 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:32 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:33 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:34 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:35 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:36 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:37 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:38 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:39 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:40 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:41 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:42 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:43 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:44 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:45 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:46 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:47 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:48 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:49 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:50 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:51 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:52 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:53 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:54 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:55 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:56 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:57 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:58 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:19:59 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:00 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:01 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:02 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:03 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:04 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:05 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:06 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:07 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:08 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:09 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:10 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:15 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:16 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:17 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:18 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:19 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:20 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:21 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:22 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:23 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:24 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:25 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:26 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:27 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:28 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:29 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:30 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:31 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:32 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:33 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:34 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:35 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:36 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:37 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:38 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:39 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:40 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:41 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:42 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:43 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:44 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:45 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:46 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:47 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:48 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:49 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:50 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:51 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:52 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:53 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:54 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:55 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:56 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:57 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:58 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:20:59 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:00 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:01 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:02 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:03 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:04 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:05 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:06 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:07 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:08 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:09 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:10 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:15 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:16 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:17 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:18 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:19 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:20 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:21 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:22 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:23 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:24 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:25 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:26 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:27 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:28 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:29 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:30 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:31 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:32 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:33 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:35 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:36 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:37 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:38 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:39 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:40 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:41 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:42 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:43 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:44 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:45 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:46 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:47 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:48 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:49 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:50 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:51 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:52 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:53 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:54 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:55 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:56 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:57 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:58 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:21:59 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:00 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:01 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:02 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:03 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:04 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:05 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:06 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:07 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:08 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:09 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:10 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:15 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:16 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:17 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:18 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:19 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:20 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:21 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:22 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:23 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:24 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:25 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:26 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:27 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:28 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:29 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:30 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:31 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:32 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:33 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:34 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:35 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:36 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:37 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:38 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:39 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:40 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:41 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:42 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:43 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:44 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:45 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:46 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:47 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:48 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:49 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:50 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:51 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:52 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:53 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:54 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:55 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:56 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:57 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:58 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:22:59 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:00 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:01 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:02 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:03 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:04 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:05 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:06 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:07 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:08 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:09 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:10 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:11 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:12 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:13 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:14 - ERROR - 9772 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:16 - INFO - 12324 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:23:16 - INFO - 12324 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:23:17 - INFO - 12324 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:23:17 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:18 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:19 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:20 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:21 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:22 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:23 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:24 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:25 - ERROR - 13968 - [wt_gateway_service.py] - wt_gateway_service - 337 - Data from the device "AlarmLed" cannot be saved, connector name is AlarmLed.
2020-09-25 14:23:32 - INFO - 3892 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:23:32 - INFO - 3892 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:23:32 - INFO - 3892 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:28:21 - INFO - 16992 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:28:21 - INFO - 16992 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:28:21 - INFO - 16992 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:32:35 - INFO - 12408 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:32:35 - INFO - 12408 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:32:35 - INFO - 12408 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:42:52 - INFO - 8392 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:42:52 - INFO - 8392 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:42:52 - INFO - 8392 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:44:42 - INFO - 8392 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 14:44:42 - INFO - 8392 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 14:45:59 - INFO - 16540 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:45:59 - INFO - 16540 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:45:59 - INFO - 16540 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 14:48:33 - INFO - 16540 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 14:48:33 - INFO - 16540 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 14:48:43 - INFO - 2832 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 14:48:43 - INFO - 2832 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 14:48:43 - INFO - 2832 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:25:25 - INFO - 2832 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:25:25 - INFO - 2832 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:25:26 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:25:26 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:25:27 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:25:57 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:25:57 - INFO - 13012 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:28:15 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:28:15 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:28:15 - ERROR - 15280 - [wt_gateway_service.py] - wt_gateway_service - 282 - Connectors - not found! Check your configuration!
2020-09-25 15:28:15 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 284 - Remote configuration is enabled forcibly!
2020-09-25 15:28:15 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:28:15 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:28:32 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:28:32 - INFO - 15280 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:28:34 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:28:34 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:28:34 - ERROR - 8680 - [wt_gateway_service.py] - wt_gateway_service - 282 - Connectors - not found! Check your configuration!
2020-09-25 15:28:34 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 284 - Remote configuration is enabled forcibly!
2020-09-25 15:28:34 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:28:34 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:28:59 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:28:59 - INFO - 8680 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:29:01 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:29:01 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:29:01 - ERROR - 15524 - [wt_gateway_service.py] - wt_gateway_service - 282 - Connectors - not found! Check your configuration!
2020-09-25 15:29:01 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 284 - Remote configuration is enabled forcibly!
2020-09-25 15:29:01 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:29:01 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:30:23 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:30:23 - INFO - 15524 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:30:25 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:30:25 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:30:25 - ERROR - 16360 - [wt_gateway_service.py] - wt_gateway_service - 282 - Connectors - not found! Check your configuration!
2020-09-25 15:30:25 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 284 - Remote configuration is enabled forcibly!
2020-09-25 15:30:25 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:30:25 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:30:41 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:30:41 - INFO - 16360 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:30:42 - INFO - 16208 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:30:42 - INFO - 16208 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:30:42 - INFO - 16208 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:32:34 - INFO - 16208 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:32:34 - INFO - 16208 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:32:37 - INFO - 17520 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:32:37 - INFO - 17520 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:32:37 - INFO - 17520 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:32:46 - INFO - 17520 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:32:46 - INFO - 17520 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:32:48 - INFO - 16848 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:32:48 - INFO - 16848 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:32:48 - INFO - 16848 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:34:27 - INFO - 16848 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:34:27 - INFO - 16848 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:34:33 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:34:33 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:34:33 - ERROR - 2192 - [wt_gateway_service.py] - wt_gateway_service - 285 - Connectors - not found! Check your configuration!
2020-09-25 15:34:33 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 287 - Remote configuration is enabled forcibly!
2020-09-25 15:34:33 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 644 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:34:33 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:35:47 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 215 - Stopping...
2020-09-25 15:35:47 - INFO - 2192 - [wt_gateway_service.py] - wt_gateway_service - 217 - The gateway has been stopped.
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:35:49 - ERROR - 14780 - [wt_gateway_service.py] - wt_gateway_service - 285 - Connectors - not found! Check your configuration!
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 287 - Remote configuration is enabled forcibly!
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 644 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:35:49 - ERROR - 14780 - [wt_gateway_service.py] - wt_gateway_service - 195 - 'WTGatewayService' object has no attribute '_WTGatewayService__subscribed_to_rpc_topics'
Traceback (most recent call last):
  File "D:/Project/wthings-gateway\wthings_gateway\gateway\wt_gateway_service.py", line 141, in __init__
    if not self.wt_client.is_connected() and self.__subscribed_to_rpc_topics:
AttributeError: 'WTGatewayService' object has no attribute '_WTGatewayService__subscribed_to_rpc_topics'
2020-09-25 15:35:49 - INFO - 14780 - [wt_gateway_service.py] - wt_gateway_service - 197 - The gateway has been stopped.
2020-09-25 15:36:46 - INFO - 14544 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:36:46 - INFO - 14544 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:36:46 - INFO - 14544 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:37:40 - INFO - 14544 - [wt_gateway_service.py] - wt_gateway_service - 215 - Stopping...
2020-09-25 15:37:40 - INFO - 14544 - [wt_gateway_service.py] - wt_gateway_service - 217 - The gateway has been stopped.
2020-09-25 15:37:45 - INFO - 13988 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:37:45 - INFO - 13988 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:37:45 - INFO - 13988 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:37:56 - INFO - 13988 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:37:56 - INFO - 13988 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:37:57 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:37:57 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:37:57 - ERROR - 17288 - [wt_gateway_service.py] - wt_gateway_service - 282 - Connectors - not found! Check your configuration!
2020-09-25 15:37:57 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 284 - Remote configuration is enabled forcibly!
2020-09-25 15:37:57 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 641 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:37:57 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 134 - Gateway started.
2020-09-25 15:38:50 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 213 - Stopping...
2020-09-25 15:38:50 - INFO - 17288 - [wt_gateway_service.py] - wt_gateway_service - 215 - The gateway has been stopped.
2020-09-25 15:38:53 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:38:53 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:38:53 - ERROR - 14660 - [wt_gateway_service.py] - wt_gateway_service - 285 - Connectors - not found! Check your configuration!
2020-09-25 15:38:53 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 287 - Remote configuration is enabled forcibly!
2020-09-25 15:38:53 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 644 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:38:53 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:39:32 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 215 - Stopping...
2020-09-25 15:39:32 - INFO - 14660 - [wt_gateway_service.py] - wt_gateway_service - 217 - The gateway has been stopped.
2020-09-25 15:39:38 - INFO - 12792 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:39:38 - INFO - 12792 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:39:38 - ERROR - 12792 - [wt_gateway_service.py] - wt_gateway_service - 286 - Connectors - not found! Check your configuration!
2020-09-25 15:39:38 - INFO - 12792 - [wt_gateway_service.py] - wt_gateway_service - 288 - Remote configuration is enabled forcibly!
2020-09-25 15:39:38 - INFO - 12792 - [wt_gateway_service.py] - wt_gateway_service - 645 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:39:38 - INFO - 12792 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:40:47 - INFO - 6204 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:40:47 - INFO - 6204 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:40:47 - ERROR - 6204 - [wt_gateway_service.py] - wt_gateway_service - 286 - Connectors - not found! Check your configuration!
2020-09-25 15:40:47 - INFO - 6204 - [wt_gateway_service.py] - wt_gateway_service - 288 - Remote configuration is enabled forcibly!
2020-09-25 15:40:47 - INFO - 6204 - [wt_gateway_service.py] - wt_gateway_service - 645 - Pair device AlarmLed - connector AlarmLed from persistent device storage - not found.
2020-09-25 15:40:47 - INFO - 6204 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:41:07 - INFO - 3288 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:41:07 - INFO - 3288 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:41:07 - INFO - 3288 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:41:16 - INFO - 12188 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:41:16 - INFO - 12188 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:41:16 - INFO - 12188 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:41:37 - INFO - 15812 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:41:37 - INFO - 15812 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:41:37 - INFO - 15812 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
2020-09-25 15:47:55 - INFO - 14632 - [wt_gateway_service.py] - wt_gateway_service - 74 - Gateway starting...
2020-09-25 15:47:55 - INFO - 14632 - [wt_gateway_service.py] - wt_gateway_service - 75 - WaveletThings IoT gateway version: 1.0
2020-09-25 15:47:55 - INFO - 14632 - [wt_gateway_service.py] - wt_gateway_service - 135 - Gateway started.
